### ISSUE TITLE
What is needed as device name?

### ISSUE THREAD

**Issue by Racer0815** [saptarshibhosale604/BT_App_Unity#1]
I tried to connect my Arduino with a HC-06 module with an Android App (in Unity) via Bluetooth. No connection could be established. I am now wondering if I have specified the device name incorrectly. ( I have the four text fields and the 3 buttons.)

**Comment by saptarshibhosale604** [comment]
1. First try to connect BT module with other application from play store like **Bluetooth Serial Monitor** (to check the Arduino and Module is working properly or not).
2. If every thing is fine then try your application to connect with module.

I hope so this will help you. And **All the best** for your project.

**Comment by Racer0815** [comment]
Hello, first of all thank you for the quick reply. I tested the Blutooth module with another app and it worked. Only with the app written in unity I could not connect.

**Comment by saptarshibhosale604** [comment]
Ok then 
1. You should check that the name of BT module for connection is written correctly
2. You can check the connection button is working properly or not
3. And you can take help with Debug.Log() for printing data in console for debugging
4. And still if its not working then if possible send the screenshot of your unity work (if its ok)

And All the best again for your project...

**Comment by Racer0815** [comment]
Ok, I'll try

**Comment by Racer0815** [comment]
I have now solved the problem, I misspelled the device name. Thanks anyway for the help.
